[package]
name = "image_paste"
version = "0.1.0"
authors = ["gabrielcfvg <56398419+gabrielcfvg@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.6"