[package]
name = "hashmaker"
version = "0.1.0"
authors = ["stalin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
md5 = "0.7.0"
sha2 = "0.9.0"
rust-crypto = "0.2.36"